f=open("C:\\Users\\shiva\\OneDrive\\Desktop\\shiv.txt",mode="r+")
# print(f.tell())
# x=f.read()
# print(f.tell())
# f.write("\nmehul attains online class")
# print(f.tell())
# f.seek(0)
# print(f.tell())
# x=f.read()
# print(x)
# f.close();


f=open("C:\\Users\\shiva\\OneDrive\\Desktop\\shiv.txt",mode="w+")
print(f.tell())
f.write("Hello guys shivam patel here..")
print(f.tell())
f.seek(0)
print(f.tell())
r=f.read()
print(f.tell())
print(r)
f.close();

f=open("C:\\Users\\shiva\\OneDrive\\Desktop\\shiv.txt",mode="a+")
print(f.tell())
f.write("\nRight now im learning python framework..")
f.write("\nwhich is used in data science..")
print(f.tell())
f.seek(0)
print(f.tell())
r=f.readlines()
print(f.tell())
for row in r:
   print(row)
